/* art_table.h - GENERATED by scripts/build_art_table.py.
 * Do not edit: Sony CDN artwork baked at build time so the
 * console needs no TMDB network access for art.
 * Titles: 27. */
#ifndef ORBISRPC_ART_TABLE_H
#define ORBISRPC_ART_TABLE_H
#include <stddef.h>
typedef struct { const char *id; const char *name; const char *icon; } art_entry_t;
static const art_entry_t ORBISRPC_ART_TABLE[] = {
    { "CUSA00021", "WATCH_DOGS™", "https://gs2-sec.ww.prod.dl.playstation.net/gs2-sec/appkgo/prod/CUSA00021_00/3/i_651e9eb6c151a5b9d2956c51f2c7aff5a72ec4e151874162adf72fb0a6be8724/i/icon0.png" },
    { "CUSA00127", "Netflix", "https://gs2-sec.ww.prod.dl.playstation.net/gs2-sec/appkgo/prod/CUSA00127_00/1/i_669d25de097f265f412a51b61b1736cfc8000b23f69842eea2f95794bc4a7d5f/i/icon0.png" },
    { "CUSA00135", "BATMAN™: ARKHAM KNIGHT", "https://gs2-sec.ww.prod.dl.playstation.net/gs2-sec/appkgo/prod/CUSA00135_00/7/i_acf6a09833040a87d9381d4dabc97bd07f5515ed644a046269ecaf2c6877b5d7/i/icon0.png" },
    { "CUSA00411", "Grand Theft Auto V", "https://gs2-sec.ww.prod.dl.playstation.net/gs2-sec/appkgo/prod/CUSA00411_00/7/i_c28a71044ce3a42dce746c4a711e70809e8a395be1fd20b2308eb438652e1b73/i/icon0.png" },
    { "CUSA00740", "Terraria", "https://gs2-sec.ww.prod.dl.playstation.net/gs2-sec/appkgo/prod/CUSA00740_00/8/i_270392835a32e8b04f2190e7c328d921ec63bffec01f59d782ab1595b02fef4b/i/icon0.png" },
    { "CUSA01004", "Sleeping Dogs: Definitive Edition", "https://gs2-sec.ww.prod.dl.playstation.net/gs2-sec/appkgo/prod/CUSA01004_00/3/i_e19df39dce5f6e1b44cf87bb4eb475f2670535709feebcc19f552bd5233514b9/i/icon0.png" },
    { "CUSA01015", "YouTube", "https://gs2-sec.ww.prod.dl.playstation.net/gs2-sec/appkgo/prod/CUSA01015_00/3/i_46a63e02581b254dbaa76d990ac4c680f6b0e7aa8cedac83c486da87e59c6da1/i/icon0.png" },
    { "CUSA01623", "God of War® III Remastered", "https://gs2-sec.ww.prod.dl.playstation.net/gs2-sec/appkgo/prod/CUSA01623_00/3/i_4235c8b4ed044602c9aa3eb7c9d6de5b7bf78e16692636bb7c548b45d60e1705/i/icon0.png" },
    { "CUSA01839", "ULTRA STREET FIGHTER IV", "https://gs2-sec.ww.prod.dl.playstation.net/gs2-sec/appkgo/prod/CUSA01839_00/1/i_d4b052c0ec1e507474a3ac9f0775644fd161c5b3c879b493c0a1150663f667ae/i/icon0.png" },
    { "CUSA03245", "Deadpool", "https://gs2-sec.ww.prod.dl.playstation.net/gs2-sec/appkgo/prod/CUSA03245_00/3/i_d1554a0ef2e2970bada64821915b84ed82696df5f3a66e8f16d00a849bb4c818/i/icon0.png" },
    { "CUSA04294", "WATCH_DOGS® 2", "https://gs2-sec.ww.prod.dl.playstation.net/gs2-sec/appkgo/prod/CUSA04294_00/2/i_8c74e4a9e267e8b93835c91b4b7304d744898c0c36c8f4173c177e33d723fc36/i/icon0.png" },
    { "CUSA04602", "Batman: Return to Arkham - Arkham City", "https://gs2-sec.ww.prod.dl.playstation.net/gs2-sec/appkgo/prod/CUSA04602_00/2/i_8760c2c3b6d1df7abf9344817c472b8c2224aa6412304679a7fc5ff1cb6c4e64/i/icon0.png" },
    { "CUSA06014", "TEKKEN™7", "https://gs2-sec.ww.prod.dl.playstation.net/gs2-sec/appkgo/prod/CUSA06014_00/3/i_1a82139fdf9aaeed91d74a6aef4e8c81e714779772e1f454da9c9afab7f9b3f3/i/icon0.png" },
    { "CUSA06545", "[PROTOTYPE® BIOHAZARD BUNDLE]", "https://gs2-sec.ww.prod.dl.playstation.net/gs2-sec/appkgo/prod/CUSA06545_00/2/i_7eca3566e84a44bf57bcce70a0f5f1f96689b9a3b2a724fa4b5a5a101e50429a/i/icon0.png" },
    { "CUSA06712", "Goat Simulator: The Bundle", "https://gs2-sec.ww.prod.dl.playstation.net/gs2-sec/appkgo/prod/CUSA06712_00/3/i_115c7d70fd47c575df7b022dab5bd10e7f248f7d69f1489334fcefe0c00a5ccd/i/icon0.png" },
    { "CUSA08992", "DRAGON BALL FighterZ", "https://gs2-sec.ww.prod.dl.playstation.net/gs2-sec/appkgo/prod/CUSA08992_00/2/i_f13f6b1fd57e69ddecc9fe236a32c2ebcbf9464e896d66ad62ed3dfadc6f5054/i/icon0.png" },
    { "CUSA09311", "Assassin's Creed® Odyssey", "https://gs2-sec.ww.prod.dl.playstation.net/gs2-sec/appkgo/prod/CUSA09311_00/2/i_ccb50a2a6659c60886f0d5e731d573e0d2ca2996b9b0d82739941fd86e4a3c30/i/icon0.png" },
    { "CUSA11995", "Marvel's Spider-Man", "https://gs2-sec.ww.prod.dl.playstation.net/gs2-sec/appkgo/prod/CUSA11995_00/2/i_a0ac52790db5fabdacd0b4318fd1d9fe9999d731745fe60b4bd229c6d7da5fbc/i/icon0.png" },
    { "CUSA13323", "Ghost of Tsushima", "https://gs2-sec.ww.prod.dl.playstation.net/gs2-sec/appkgo/prod/CUSA13323_00/8/i_79e6fad7f6d7610ec23583faf0f43c6a09057193f811583539f88f632cbe8fd7/i/icon0.png" },
    { "CUSA14909", "SpongeBob SquarePants: Battle For Bikini Bottom - Rehydrated", "https://gs2-sec.ww.prod.dl.playstation.net/gs2-sec/appkgo/prod/CUSA14909_00/4/i_c5bb0ce1278e0c7f13895b383a1e694bf0c1d2b3a4c94bec6af059d05a2da865/i/icon0.png" },
    { "CUSA18795", "Skater XL", "https://gs2-sec.ww.prod.dl.playstation.net/gs2-sec/appkgo/prod/CUSA18795_00/8/i_5aaf5b8c67ce2d70cc245b7a69c74ba38c635b305da25c1bbdb1a933f392fdca/i/icon0.png" },
    { "CUSA20177", "Marvel's Spider-Man: Miles Morales", "https://gs2-sec.ww.prod.dl.playstation.net/gs2-sec/appkgo/prod/CUSA20177_00/4/i_b6404ea17d83197d2aa76cfaa8387cf5c98d6435632cef3673336c6ea25f49aa/i/icon0.png" },
    { "CUSA20499", "Cuphead", "https://gs2-sec.ww.prod.dl.playstation.net/gs2-sec/appkgo/prod/CUSA20499_00/1/i_6ae1f36557867972ba228657f55f89b217db4ea7e4e9f7946d5a06c696749659/i/icon0.png" },
    { "CUSA24899", "Stray", "https://gs2-sec.ww.prod.dl.playstation.net/gs2-sec/appkgo/prod/CUSA24899_00/1/i_9d292798534ec68c44fdaed2d5822cae587aecd40087095f7b6ee446fac1f2cf/i/icon0.png" },
    { "CUSA26618", "Grand Theft Auto: San Andreas – The Definitive Edition", "https://gs2-sec.ww.prod.dl.playstation.net/gs2-sec/appkgo/prod/CUSA26618_00/9/i_6ddd21f2e6e2ca7b11d6b9ef4ebffc7f0ffbd0feb540c35c14136ccdd2dc5808/i/icon0.png" },
    { "CUSA33151", "Assassin's Creed® Mirage", "https://gs2-sec.ww.prod.dl.playstation.net/gs2-sec/appkgo/prod/CUSA33151_00/4/i_cf93eb08445648801628c6c458c966e2e6ca3c0b524666c8b308f514d59bb541/i/icon0.png" },
    { "CUSA09303", "Assassin's Creed® Odyssey", "https://gs2-sec.ww.prod.dl.playstation.net/gs2-sec/appkgo/prod/CUSA09303_00/3/i_d6b485c473b4b3d739197a5f020aeb7428f69d6c29e0dda514f6db41916dc3b6/i/icon0.png" },
};
#define ORBISRPC_ART_TABLE_N (sizeof ORBISRPC_ART_TABLE / sizeof ORBISRPC_ART_TABLE[0])
#endif
